name: catalog_update

concurrency: 
  group: apps_catalog_update

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  publish_catalog:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/truenas/apps_validation:latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: 'Get pips'
        run: /bin/ps -aux
      - name: 'Waiting a little bit'
        run: /bin/sleep 120
      - name: 'Getting PID agains'
        run: /bin/ps -aux
      - name: 'Find all catalog read'
        run: find / -name "*catalog_read*"
      - name: 'Cat update file'
        run: cat /usr/local/bin/apps_catalog_update
      - name: Add catalog json as a safe directory
        run: |
          /bin/bash -c "PWD=${pwd}; git config --global --add safe.directory $PWD"
      - name: 'Check middleware client connection'
        run: python3 -c "from truenas_api_client import Client; obj = Client(); print(obj.call('core.ping'))"
      - name: Publish catalog
        run: |
          /bin/bash -c "PWD=${pwd}; /usr/local/bin/apps_catalog_update publish --path $PWD"
      - name: Check untracked files existence
        run: echo "CHANGES=$(git -C $(pwd) --no-pager status --porcelain | wc -l)" >> "$GITHUB_ENV"

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: env.CHANGES != '0'
        with:
            commit_message: "Publish new changes in catalog [skip ci]"
            commit_user_name: sonicaj
            commit_user_email: waqarsonic1@gmail.com
            commit_author: sonicaj <waqarsonic1@gmail.com>
      - name: Update catalog
        if: env.CHANGES != '0'
        run: |
          /bin/bash -c "PWD=${pwd}; /usr/local/bin/apps_catalog_update update --path $PWD"
      - uses: stefanzweifel/git-auto-commit-action@v4
        if: env.CHANGES != '0'
        with:
            commit_message: "Update catalog changes [skip ci]"
            commit_user_name: sonicaj
            commit_user_email: waqarsonic1@gmail.com
            commit_author: sonicaj <waqarsonic1@gmail.com>
